config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :doses, only: [ :destroy ]

  # get '/search', to: "pages#search"
  get '/search', to: "cocktails#index"
  get '/story', to: "pages#story"

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :season, inclusion: { in: ["Spring", "Summer", "Autumn", "Winter", ""] }, allow_blank: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :rating, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])

    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cocktails = Cocktail.last(3)
    @topcocktails = Cocktail.last(3)
  end

  def story
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_searchnavbar.html.erb
<div class="searchbar flex mx-20px pb-10px bb-cm">
  <i class="fas fa-search"></i>
  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: "border-0 width-70vw focus-outline-none", placeholder: "Looking for something more specific?" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<%= render 'searchnavbar' %>

<div class="searchresults p-40px">
  <p class="mb-50px">Search results for "<%= params[:query].nil? ? "All" : params[:query] %>" (<%= @cocktails.count %> results)</p>

  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-cm-vertical mb-40px">
            <%= link_to cocktail_path(cocktail) do %>
              <div class="card-cm-vertical-top background-picture" style="background-image: url(<%= asset_path "#{cocktail.photo}" %>);"></div>
            <% end %>
            <div class="card-cm-vertical-bottom">
              <p class="font-13px margin-strip">WITH BAE • AT THE MOUNTAIN</p>
              <%= link_to cocktail_path(cocktail) do %>
                <h5 class="margin-strip mt-10px"><%= cocktail.name %></h5>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a cocktail</h1>

<%= simple_form_for (@cocktail) do |f| %>

  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Share my cocktail", class: "btn btn-default" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<% @cocktail.doses.each do |dose| %>
  <%= dose.description %>
  <%= dose.ingredient.name %>
  <%= link_to "Delete this dose", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }  %>
<% end %>

<%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail), class: "btn btn-default"  %>


<%= cl_image_tag(@cocktail.photo,
      width: 400, height: 300, crop: :fill) %>


<h1>Reviews</h1>

<% @cocktail.reviews.each do |review| %>
  <%= review.content %>
  <%= review.rating %>
<% end %>

<h1>Add a review</h1>

<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: 'select2' } %>
  <%= f.input :description %>
  <%= f.submit "Add dose", class: "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail Memories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-cm-center">
  <div class="banner-cm-2halfs">
    <div class="banner-cm-half background-picture" style="background-image: url(<%= asset_path 'cocktail1.png' %>);"></div>
    <div class="banner-cm-half text-center banner-cm-center-center-column p-20px">
      <h1 class="margin-strip mb-30px">Because we believe<br>that a cocktail tells a story</h1>
      <p class="margin-strip mb-30px">
        Let’s raise our glasses to these Proustian moments
        <br>Past, future or present
        <br>Let’s make these moments last forever
        <br>One drop, this exquisite taste
        <br>Always takes me back</p>
        <%= link_to "SHARE YOUR COCKTAIL >", new_cocktail_path, class: "button-cm" %>
    </div>
  </div>
</div>

<div class="wrapper-cm-center text-center">
  <h4 class="mb-80px">Our WINTER cocktails</h4>
  <div class="container mb-80px">
    <div class="row">
      <% @topcocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-cm-vertical">
            <%= link_to cocktail_path(cocktail) do %>
              <div class="card-cm-vertical-top background-picture" style="background-image: url(<%= asset_path "#{cocktail.photo}" %>);"></div>
            <% end %>
            <div class="card-cm-vertical-bottom">
              <p class="font-13px margin-strip">WITH <%= cocktail.person.upcase %> • AT <%= cocktail.moment.upcase %> • <%= cocktail.season.upcase %></p>
              <%= link_to cocktail_path(cocktail) do %>
                <h5 class="margin-strip mt-10px"><%= cocktail.name %></h5>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to "SEE MORE >", search_path, class: "button-cm" %>
</div>

<div class="wrapper-cm-center background-picture-bottom height-100vh wrapper-flex-right" style="background-image: url(<%= asset_path 'cocktail2.png' %>);">
  <div class="banner-cm-half-bg-transparent text-center banner-cm-center-center-column p-20px">
    <p class="margin-strip mb-30px white-text">OUR COCKTAIL OF THE MONTH</p>
    <h1 class="margin-strip mb-30px white-text">WHISKY SOUR</h1>
    <p class="margin-strip mb-30px white-text">
      Perfect for the summer <br>
      Reminisce over the past and invent the future
    </p>
      <%= link_to "HOW TO SHAKE IT >", new_cocktail_path, class: "button-cm-transparent" %>
  </div>
</div>

<div class="wrapper-cm-center text-center">
  <div class="list-cm">
    <h4>Our MOST-VOTED cocktails</h4>
    <% @cocktails.each do |cocktail| %>
      <div class="card-cm" data-aos="fade-in">
        <%= link_to cocktail_path(cocktail), class: "width-50pc" do %>
          <div class="height-100pc width-100pc background-picture" style="background-image: url(<%= asset_path "#{cocktail.photo}" %>);"></div>
        <% end %>
        <div class="card-cm-half flex flexdirection-column justifycontent-center alignitems-flexstart pl-40px">
          <p class="font-13px margin-strip">WITH <%= cocktail.person.upcase %> • AT <%= cocktail.moment.upcase %> • <%= cocktail.season.upcase %></p>
          <%= link_to cocktail_path(cocktail) do %>
            <h5><%= cocktail.name %></h5>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/story.html.erb
<h1>Story page</h1>

app/views/shared/_footer.html.erb
<div class="footer-cm">
  <div class="footer-cm-left">
    <h3 class="margin-strip mb-10px darkmediumgray-text">Get in touch</h3>
    <%= mail_to "contact@cocktailmemories.com" do %>
      <p class="margin-strip">contact@cocktailmemories.com</p>
    <% end %>
  </div>
  <div class="footer-cm-right">
    <div class="newsletter">
      <p class="margin-strip">SIGN UP FOR OUR NEWSLETTER ></p>
    </div>
    <div class="flexbox-startend">
      <p class="font-13px darkmediumgray-text">Made by Studio Bole</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-cm">
  <div class="navbar-cm-left width">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class: "navbar-cm-logo" %>
    <% end %>
  </div>
  <div class="navbar-cm-middle">
    <%= link_to root_path do %>
      <h3 class="margin-strip">Cocktail Memories</h3>
    <% end %>
  </div>
  <div class="navbar-cm-right width">
    <%= form_tag search_path, method: :get, class: "flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control navbar-cm-search", placeholder: "Cocktail?" %>
      <%= button_tag class: "button-strip margin-strip padding-strip" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="navbar-cm-2 text-center">
  <div class="navbar-cm-2-middle">
    <%= link_to search_path do %>
      <p class="margin-strip">ALL COCKTAILS</p>
    <% end %>
    <%= link_to story_path do %>
      <p class="margin-strip">THE STORY</p>
    <% end %>
  </div>
</div>